x-environment: &default-env
  env_file:
    - ./envs/infra.env

services:
  nginx:
    image: nginx:latest
    container_name: infra-nginx
    depends_on:
      - api_gateway
    volumes:
      - ../services/api_gateway/staticfiles:/app/staticfiles:ro
      - ../services/api_gateway/media:/app/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8100:80"   # browser will now access Django via Nginx
    networks:
      - loggerhub_net
  
  nginx_processor:
    image: nginx:latest
    container_name: processor-nginx
    depends_on:
      - processor_service
    volumes:
      - ../services/processor_service/staticfiles:/app/staticfiles:ro
      - ../services/processor_service/media:/app/media:ro
      - ./nginx/processor.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8101:80"   # browser → localhost:8101 → nginx_processor
    networks:
      - loggerhub_net

  postgres:
    build:
      context: ./postgres
    restart: unless-stopped
    env_file:
      - ./envs/infra.env
    volumes:
      - loggerhub_postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - loggerhub_net

  redis:
    image: redis:7
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - loggerhub_redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6389:6379"    # host 6389 -> container 6379 (isolated)
    networks:
      - loggerhub_net

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    env_file:
      - ./envs/infra.env
    volumes:
      - loggerhub_minio_data:/data
      - ./minio:/docker-entrypoint-init:ro
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"   # MinIO API
      - "9101:9001"   # MinIO Console
    networks:
      - loggerhub_net

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - discovery.type=single-node
      - cluster.name=loggerhub-opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - loggerhub_opensearch_data:/usr/share/opensearch/data
      - ./opensearch/init:/usr/share/opensearch/init:ro
    ports:
      - "9300:9200"  # OpenSearch REST
      - "9301:9600"  # Perf analyzer
    networks:
      - loggerhub_net

  api_gateway:
    build:
      context: ../services/api_gateway
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}     # Pick from .env (args available at build time)
    env_file:
      - ./envs/api_gateway.env
    environment:
      - APP_ENV=${APP_ENV}      # Pass it into container too (environment available at runtine inside container)
    depends_on:
      - postgres
      - redis
      - minio
      - opensearch
    volumes:
      - ../services/api_gateway:/app:cached
    # ports: # Ngnx handles this
    #   - "8100:8000"
    networks:
      - loggerhub_net
  
  processor_service:
    build:
      context: ../services/processor_service
      dockerfile: Dockerfile
    env_file:
      - ./envs/processor.env
    depends_on:
      - postgres
      - redis
      - minio
      - opensearch
    volumes:
      - ../services/processor_service:/app:cached
    # ports:
    #   - "8101:8001"
    networks:
      - loggerhub_net

  processor_worker:
    build:
      context: ../services/processor_service
      dockerfile: Dockerfile
    env_file:
      - ./envs/processor.env
    command: ["/entrypoint.sh", "celery", "-A", "config", "worker", "-l", "info"]
    depends_on:
      - processor_service
      - redis
      - postgres
    networks:
      - loggerhub_net



  search_service:
    build:
      context: ../services/search_service
      dockerfile: Dockerfile
    env_file:
      - ./envs/search.env
    depends_on:
      - postgres
      - opensearch
    volumes:
      - ../services/search_service:/app:cached
    ports:
      - "8102:8002"
    networks:
      - loggerhub_net

  ingestion_service:
    build:
      context: ../services/ingestion_service
      dockerfile: Dockerfile
    env_file:
      - ./envs/ingestion.env
    ports:
      - "9102:9002"
    depends_on:
      - redis
      - minio
    networks:
      - loggerhub_net

volumes:
  loggerhub_postgres_data:
  loggerhub_redis_data:
  loggerhub_minio_data:
  loggerhub_opensearch_data:

networks:
  loggerhub_net:
    name: loggerhub_net
    driver: bridge


